from pathlib import Path
import csv,json
A=Path(__file__).resolve().parent
def rows(p):return list(csv.DictReader((A/p).open(encoding='utf-8-sig')))
s=(A/'Sources/Manuscript_live.txt').read_text(encoding='utf-8');changes=[]
def rep(old,new,why):
 global s
 assert old in s,old[:100]
 s=s.replace(old,new);changes.append(dict(reason=why,before=old,after=new))
def para(prefix,new,why):
 old=next(x for x in s.splitlines() if x.startswith(prefix));rep(old,new,why)
rep('0.281, 95% confidence interval −0.109 to 0.672','0.251, 95% confidence interval −0.111 to 0.614','Abstract: Hwang sample-size correction')
rep('g = 0.390 (0.205 to 0.575; I² = 52.6%)','g = 0.380 (0.200 to 0.561; I² = 49.4%)','Abstract: corrected overall')
rep('usable numerical estimates from nine datasets','usable numerical estimates from nine analysis clusters, one containing two independent experiments','Distinguish report clusters from independent experiments')
rep('Positive effects indicated an increase in the measured EEG feature associated with improved cognition, not necessarily cognitive improvement.','Positive effects indicated an increase in the coded EEG feature; the sign alone did not establish cognitive benefit or an EEG–cognition association.','Separate physiology from cognitive benefit')
rep('Memory had a pooled estimate of g = 0.281 (k = 7; 95% CI -0.109 to 0.672; p = 0.128; I² = 65.6%; τ² = 0.093), with a 95% prediction interval of -0.561 to 1.124.','Memory had a pooled estimate of g = 0.251 (k = 7; 95% CI -0.111 to 0.614; p = 0.141; I² = 56.8%; τ² = 0.066), with a 95% prediction interval of -0.473 to 0.975.','Primary memory correction')
rep('The small evidence base, unmodified Hartung–Knapp inference and absence of multiplicity adjustment across domains warrant caution.','The small evidence base, unmodified Hartung–Knapp inference and absence of multiplicity adjustment across domains warrant caution. A modified-HK sensitivity retained g = 0.617 but gave a 95% CI of -0.075 to 1.310 (p = 0.062).','Required modified-HK sensitivity')
para('The secondary mixed-domain estimate was','The secondary mixed-domain estimate was g = 0.380 (k = 17; 95% CI 0.200 to 0.561; p < 0.001; I² = 49.4%; τ² = 0.047), with Q₁₆ = 33.659. Its prediction interval crossed zero (-0.115 to 0.876; Table 1, Figure 4).','Correct overall and heterogeneity')
loo=rows('Working_corrected/Outputs/LOO_Overall_cognition.csv');rr=rows('Outputs/corrected_rounding_sensitivity.csv')
ranges=[]
for d in ['Overall cognition','Memory','Executive / sustained attention']:
 vals=[float(x['g']) for x in rr if x['domain']==d]
 if vals:ranges.append(f'{d.lower()} {min(vals):.4f} to {max(vals):.4f}')
para('Overall leave-one-out estimates ranged',f"Overall leave-one-out estimates ranged from {min(float(x['estimate']) for x in loo):.3f} to {max(float(x['estimate']) for x in loo):.3f}, with positive confidence intervals. This stability did not remove uncertainty within the primary domains. Across 128 joint digitization and paired-t rounding scenarios, ranges were: {'; '.join(ranges)}. These are robustness ranges, not confidence intervals. Corrected sensitivity results and retained/excluded cohort IDs are in the dated integrity audit; publication supplements require replacement with those outputs.",'Regenerate sensitivity ranges')
mv=next(x for x in rows('Working_corrected/Outputs/multilevel.csv') if x['variant']=='components' and float(x['rho'])==.5 and float(x['paired_r'])==.5)
para('Moderator tests were not significant',f"Moderator tests were not significant after Holm correction (population, adjusted p = 0.446; schedule, 0.401; domain group, 0.446). These tests do not establish equivalent effects across groups. The selected-outcomes estimate at ρ = 0.50 was g = {float(mv['g']):.3f} (95% CI {float(mv['lo']):.3f} to {float(mv['hi']):.3f}; 23 effects from 17 cohorts; Satterthwaite df = {float(mv['df']):.2f}). This is not an exhaustive all-outcomes analysis: additional reported outcomes require an explicit ascertainment and selection policy. The separate external expansion yielded g = 0.440 (k = 23; 95% CI 0.282 to 0.599). The separate raw MMSE estimate was 1.045 points (k = 3; 95% CI -2.428 to 4.519; p = 0.325).",'Correct moderators, multilevel and expansion')
para('Only the secondary overall set met','Only the secondary overall set met the minimum size for small-study analyses. The Egger-type test gave t₁₅ = 1.977 (p = 0.067), and Begg’s test gave τ = 0.265 (p = 0.151). Trim-and-fill added four hypothetical studies (g = 0.281; Wald 95% CI 0.107 to 0.455). PET estimated g = 0.036 (95% CI -0.356 to 0.428), PEESE estimated g = 0.206 (-0.034 to 0.447), and the exploratory selection model estimated g = 0.205 (Wald 95% CI 0.046 to 0.363). These divergent estimates do not establish that reporting bias is absent and qualify the positive secondary overall finding.','Correct small-study sensitivities')
para('Across populations, stimulation parameters,','Memory and global cognition had positive estimates with confidence intervals including zero. Executive function/sustained attention and the secondary overall estimate had confidence intervals excluding zero under the stated unmodified-HK method; the overall prediction interval included zero. The executive/attention result was sensitive to modified-HK inference. Population and treatment schedule did not significantly moderate outcomes, but the tests were too limited to establish equivalence. Exploratory pulse, device, sham-dose and industry comparisons did not establish parameter effects; sparse groups and confounding prevent an optimal-protocol conclusion. EEG treatment effects and concurrent associations do not establish validated individual prediction or benefit from adaptive treatment.','Repair Discussion errors and incomplete sentence without adding a favorable narrative')
rep('g = 0.281 and 0.399, respectively','g = 0.251 and 0.399, respectively','Conclusion numerical correction')
rep('Lower active-condition delta power at Fp1, one week post-treatment. Source-summary estimate; not independently reconstructed.','Lower active-condition delta power at Fp1, one week post-treatment. Arithmetic reconstructed from adjusted means and reported SDs; ordinary independent-group variance does not recover ANCOVA uncertainty. Descriptive and provisional.','Mehdizadeh arithmetic/source distinction')
rep('CDA set-size contrast during visual working memory; within-paper aggregate of two crossover experiments. Source-summary estimate; not independently reconstructed.','CDA set-size contrast during visual working memory; within-paper aggregate of two crossover experiments. Arithmetic independently reconstructed from paired t statistics using the recorded paired-difference standardization and inverse-variance aggregation.','Zhao arithmetic reconstruction and standardizer')
rep('Arithmetic reconstruction of 205 estimates does not establish that the source assumptions are valid.','Arithmetic reconstruction of all 207 retained estimates, including the Zhao aggregate and Mehdizadeh contrast, does not establish that the source assumptions are valid.','Additional EEG reconstructions')
rep('An exploratory multilevel model used 23 harmonized outcomes','An exploratory multilevel model used 23 selected harmonized outcomes','Qualify outcome coverage')
rep('Additional planned moderators lacked sufficient data.','A dated feasibility assessment distinguished missing metadata from sparse or confounded contrasts. Source-audited pulse, device, sham-dose and industry comparisons were exploratory; age, wavelength, target distribution and session-count analyses were not treated as validated explanatory models.','Parameter feasibility rather than blanket omission')
rep('Independent Python calculations checked all 17 revised effects and variances under three paired-correlation settings and five REML/Hartung–Knapp models.','The dated integrity audit independently checked representative effects under three paired-correlation settings and four principal REML/Hartung–Knapp models in Python, with additional metafor formula cross-checks. It corrected Hwang sample sizes from 20 to 15 per selected arm, Hwang sham classification, and three industry flags. Arithmetic verification remained separate from source verification.','Update audit provenance')
old=next(x for x in s.splitlines() if x.startswith('DF completed critical appraisal'))
rep(old,old+' [AUDIT QUERY: DF reports finalized judgments and agreement of at least 90%; provide the final item-level file, agreement numerator/denominator, adjudication record and mapping to major-risk flags. The accessible summary contains older, lower agreement values and does not independently substantiate these statements. Absence of a flag is not a low-risk judgment.]','Retain author statement while requesting its supporting evidence')
start=s.index('Table 1. Harmonized primary cognitive domains and secondary overall estimate');end=s.index('Figure 1. PRISMA flow',start)
rep(s[start:end],'Table 1. Harmonized primary cognitive domains and secondary overall estimate\n\n'+(A/'Outputs/principal_results.md').read_text(encoding='utf-8')+'\n\nCorrected values are the audited working results. Reproduced values document the superseded v2 input. REML and unmodified HK remain primary; the secondary overall estimate combines domains.\n\n','Replace Table 1 with traceable original/corrected results')
header='AUDITED WORKING TEXT — 17 September 2026\nSource: frozen live Manuscript 1.5. Targeted audit corrections only; not a submission-ready document. Citations/formatting must be restored in the authoring file. Unresolved source and appraisal queries remain. No live document was edited. Figures must be replaced with Working_corrected/Figures outputs.\n\n'
(A/'Working_corrected/Manuscript_audited_working.txt').write_text(header+s,encoding='utf-8')
(A/'Outputs/manuscript_change_log.json').write_text(json.dumps(changes,ensure_ascii=False,indent=2),encoding='utf-8')
out=['# Manuscript correction list','', 'The separate working text implements the numbered changes below. The original/live manuscript is preserved. The JSON change log contains exact before/after text.','']
out += [f'{i}. {x["reason"]}.' for i,x in enumerate(changes,1)]
out += ['', '## Required before submission','', '- Reconcile final item-level JBI assessments, agreement records and major-risk mapping; do not label unflagged studies low risk.', '- Resolve the source-specific uncertainties in cohort_effect_provenance.csv, including supplements, analyzed samples and digitized denominators. Obtain the He/Bastola author-data records supporting EEG transcription.', '- Establish an exhaustive outcome inventory and selection policy before describing the 23-effect model as all outcomes; Lee TBI reports additional extractable endpoints.', '- Correct the historical Tang PW row in a versioned master; retain its audit trail and keep it out of the current main effect.', '- Replace publication forests and dependent tables/supplements from corrected outputs. Update the dated SAP amendment and pointers without changing historical prespecification claims.', '- Complete the screening/report-to-study ledger, PRISMA counts, search dates, safety denominators, repository and author queries. These were not certified by this statistical audit.', '- Restore reference-manager formatting and add complete references for included studies and statistical methods; the working text preserves existing references rather than inventing missing entries.', '- Keep EEG descriptive and separate treatment effects, concurrent associations, externally validated prediction, and randomized adaptive-treatment evidence. Preserve the NeoPhotera disclosure.', '', 'The limited Discussion replacement fixes verified interpretation errors; it is not a full narrative rewrite.']
(A/'MANUSCRIPT_CORRECTIONS.md').write_text('\n'.join(out)+'\n',encoding='utf-8')
print(f'Applied {len(changes)} targeted corrections.')
